# Generated by Django 4.0.1 on 2022-01-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_likecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='DisslikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disslike_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='DisslikeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disslikecomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.commentpost')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
            ],
        ),
    ]
