# Generated by Django 4.0.1 on 2022-02-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_likepost_disslikepost_disslikecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
