# Generated by Django 4.0.1 on 2022-02-03 16:25

import datetime
from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_commentpost_created_at_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='created_at',
            field=models.DateField(verbose_name=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Now(), '-', django.db.models.expressions.Value(datetime.timedelta(days=365)))),
        ),
    ]
