# Generated by Django 4.0.1 on 2022-02-04 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_commentpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 4, 19, 53, 44, 703963, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 4, 19, 53, 44, 703767, tzinfo=utc)),
        ),
    ]
