# Generated by Django 4.0.1 on 2022-02-04 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_commentpost_updated_at_alter_commentpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='updated_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
