# Generated by Django 4.0.1 on 2022-01-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('myapp', '0001_initial'), ('myapp', '0002_customer_customersettings'), ('myapp', '0003_alter_customersettings_customer'), ('myapp', '0004_auto_20220130_1245')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_color', models.CharField(max_length=24)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='myapp.customer')),
            ],
        ),
    ]
