# Generated by Django 4.0.1 on 2022-01-29 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_customersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersettings',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='myapp.customer'),
        ),
    ]
