# Generated by Django 4.0.1 on 2022-01-29 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Book Title')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Book_Catalog.author')),
            ],
            options={
                'verbose_name': 'Books',
            },
        ),
    ]
