# Generated by Django 4.0.1 on 2022-01-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Catalog', '0002_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Authors', 'verbose_name_plural': 'Author'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Books', 'verbose_name_plural': 'Book'},
        ),
    ]
