# Generated by Django 4.0.1 on 2022-01-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customersettings_customer'),
        ('Book_Catalog', '0006_alter_book_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub',
            field=models.ManyToManyField(related_name='Subs', to='Book_Catalog.Author', verbose_name='Sub Authors'),
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='Book_Catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.article')),
            ],
        ),
    ]
