# Generated by Django 4.0.1 on 2022-01-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Catalog', '0007_alter_book_sub_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='is_own',
            field=models.BooleanField(default=True, verbose_name='Взята'),
        ),
    ]
