# Generated by Django 4.0.1 on 2022-01-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Catalog', '0008_reader_is_own'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='is_own',
            field=models.BooleanField(default=True, verbose_name='Book taken'),
        ),
    ]
